namespace RecordStoreDemo.Common.Constants;

public class ProductMetaFields
{
    public static readonly List<string> MusicGenres = new()
    {
        "Blues",
        "Classical",
        "Country",
        "Electronic",
        "Folk",
        "Hip-Hop",
        "International",
        "Jazz",
        "Local / East Coast",
        "Metal",
        "Non-Music",
        "Punk",
        "Rock / Pop",
        "Soul / R&B",
        "Soundtrack",
    };

    public static readonly List<string> MusicStyles = new()
    {
        "Alternative Pop",
        "Alternative R&B",
        "Alternative Rap",
        "Alternative Rock",
        "Ambient",
        "Americana",
        "Bebop",
        "Black Metal",
        "Bluegrass",
        "Blues Rock",
        "Children's",
        "Cloud Rap",
        "Comedy",
        "Contemporary Jazz",
        "Cool Jazz",
        "Dance",
        "Death Metal",
        "Disco",
        "Doom Metal",
        "Downtempo",
        "Dream Pop",
        "Drill",
        "Dubstep",
        "East Coast Rap",
        "Easy Listening",
        "Electric Blues",
        "Emo",
        "Experimental",
        "Folk Blues",
        "Folk Metal",
        "Folk Rock",
        "Francophone",
        "Free Jazz",
        "Funk",
        "Fusion",
        "Future Jazz",
        "Gangsta Rap",
        "Garage Rock",
        "Glam Rock",
        "Goth",
        "Grindcore",
        "Grunge",
        "Hard Rock",
        "Hardcore Punk",
        "Heavy Metal",
        "Holiday",
        "House & Techno",
        "IDM",
        "Indie Folk",
        "Indie Pop",
        "Indie Rock",
        "Industrial",
        "Instrumental Hip-Hop",
        "Jazz Rap",
        "Leftfield",
        "Math Rock",
        "Melodic Hardcore",
        "Metalcore",
        "Midwest Rap",
        "Motown",
        "Neo-Classical",
        "Neo-Soul",
        "New Age",
        "New Wave",
        "Noise Rock",
        "Nu-Metal",
        "Pop",
        "Pop Punk",
        "Pop Rap",
        "Post-Hardcore",
        "Post-Punk",
        "Post-Rock",
        "Power Metal",
        "Power Pop",
        "Progressive Rock",
        "Psychedelic",
        "Punk Rock",
        "Reggae / Dub",
        "Rock n' Roll",
        "Screamo",
        "Shoegaze",
        "Singer-Songwriter",
        "Ska",
        "Slowcore",
        "Sludge Metal",
        "Soul Jazz",
        "Southern Rap",
        "Southern Rock",
        "Spiritual",
        "Spoken Word",
        "Street Rap",
        "Swing / Big Band",
        "Symphonic Metal",
        "Synth Pop",
        "Synthwave",
        "Thrash Metal",
        "Trap",
        "Trip-Hop",
        "Tropicalia",
        "Underground Rap",
        "Vocal Jazz",
        "West Coast Rap"
    };

    public static readonly List<string> Tags = new()
    {
        "Tone Poet",
        "Speaker's Corner",
        "MFSL",
        "Acoustic Sounds",
        "Half-Speed Mastered",
        "Mono",
        "Criterion Collection",
        "Arrow Video",
        "Funko! Pop",
        "Action Figure",
        "Taz Exclusive",
        "Taz Merch",
        "Record Store Day",
        "Clearance"
    };
}
